# Generated by Django 5.2.7 on 2025-11-04 23:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(help_text='Ordem da etapa (0 a 12, sendo 0 o tema zero)', unique=True)),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('dupla', 'Dupla (2 dispositivos)'), ('trio', 'Trio (3 dispositivos)'), ('grupo', 'Grupo (todos os dispositivos)')], default='individual', max_length=20)),
                ('pista', models.TextField(help_text='Texto ou descrição da pista')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='etapas/')),
                ('resposta_correta', models.CharField(blank=True, help_text='Resposta esperada (deixe vazio se for apenas QR code)', max_length=200)),
                ('qrcode_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qrcode_imagem', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('requer_tempo_minimo', models.BooleanField(default=False, help_text='Etapa só pode ser completada após tempo mínimo')),
                ('tempo_minimo_segundos', models.IntegerField(default=0, help_text='Tempo mínimo em segundos desde início da etapa')),
                ('ativa', models.BooleanField(default=True, help_text='Se está ativa no jogo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('etapa_anterior', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxima_etapa_rel', to='etapas.etapa')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='LogAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login', 'Login'), ('qrcode', 'QR Code Escaneado'), ('resposta', 'Resposta Enviada'), ('avanco', 'Avanço de Etapa')], max_length=20)),
                ('descricao', models.TextField()),
                ('dados_extra', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etapas.etapa')),
            ],
            options={
                'verbose_name': 'Log de Ação',
                'verbose_name_plural': 'Logs de Ações',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('conclusao', models.DateTimeField(blank=True, null=True)),
                ('dispositivos_validados', models.JSONField(default=list, help_text='Lista de session_keys dos dispositivos que validaram')),
                ('qrcode_escaneado', models.BooleanField(default=False)),
                ('resposta_validada', models.BooleanField(default=False)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='etapas.etapa')),
            ],
            options={
                'verbose_name': 'Progresso da Etapa',
                'verbose_name_plural': 'Progressos das Etapas',
                'unique_together': {('equipe', 'etapa')},
            },
        ),
    ]
