# Generated by Django 6.0.2 on 2026-03-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelOsciloscopio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='MISSÃO DESCONHECIDA', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Texto introdutório da missão')),
                ('tipo_func', models.CharField(choices=[('sen', 'Seno'), ('cos', 'Cosseno')], default='sen', max_length=3)),
                ('A', models.IntegerField(default=0, help_text='Deslocamento vertical (inteiro ≥ 0)')),
                ('B', models.IntegerField(default=1, help_text='Amplitude (inteiro ≥ 1)')),
                ('C', models.IntegerField(default=1, help_text='Frequência angular (inteiro ≥ 1)')),
                ('D', models.IntegerField(default=0, help_text='Fase (inteiro ≥ 0)')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
    ]
